version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11

    working_directory: /go/src/github.com/franckverrot/trek

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-pkg-cache

      - run: GO111MODULE=on make all

      - save_cache:
          key: v1-pkg-cache
          paths:
            - "/go/pkg"